hl.config({ autogenerated = false })

local modules = {
	"config.autostart",
	"config.environment",
	"config.variables",
	"config.monitor",
	"config.keybinds",
	"config.animations",
	"config.decorations",
	"config.windowrule",
	"config.input",
}

for _, module in ipairs(modules) do
	local success, err = pcall(require, module)

	if not success then
		print("ERROR AL CARGAR MÓDULO: " .. module)
		print("Detalles: " .. tostring(err))

		local title = "Error en Hyprland"
		local message = "Fallo al cargar el módulo:\\n" .. module
		local cmd = string.format("notify-send -u critical '%s' '%s'", title, message)

		hl.dsp.exec_cmd(cmd)
	end
end
