source-file ~/.config/tmux/tmux.reset.conf
set-option -g default-terminal 'tmux-256color'
set-option -ga terminal-overrides ',xterm-ghostty:RGB'

set -g prefix ^w
set -g base-index 1
set -g detach-on-destroy off     # no salir de tmux al cerrar una sesion
set -g escape-time 0             # cero delay - vital para neovim
set -g renumber-windows on       # renumerar ventanas automaticamente
set -g set-clipboard on          # usar el copiar del sistema
set -g history-limit 100000      # Reemplaza a tmux-sensible (más historial)
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

# lista de plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'christoomey/vim-tmux-navigator'

# theme
set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @catppuccin_flavor 'macchiato'
set -g @catppuccin_window_status_style "none"
set -g status-left "#{E:@catppuccin_status_session}#[bg=default]  "
set -g status-left-length 100
set -g status-right ""

run '~/.config/tmux/plugins/tpm/tpm'
